//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 03:05:17 PM IST 
//


package com.bhavna.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="empName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="empSal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empId",
    "empName",
    "desg",
    "empSal"
})
@XmlRootElement(name = "EmployeeRequest")
public class EmployeeRequest {

    protected int empId;
    @XmlElement(required = true)
    protected String empName;
    @XmlElement(required = true)
    protected String desg;
    protected double empSal;

    /**
     * Gets the value of the empId property.
     * 
     */
    public int getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     */
    public void setEmpId(int value) {
        this.empId = value;
    }

    /**
     * Gets the value of the empName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets the value of the empName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpName(String value) {
        this.empName = value;
    }

    /**
     * Gets the value of the desg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesg() {
        return desg;
    }

    /**
     * Sets the value of the desg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesg(String value) {
        this.desg = value;
    }

    /**
     * Gets the value of the empSal property.
     * 
     */
    public double getEmpSal() {
        return empSal;
    }

    /**
     * Sets the value of the empSal property.
     * 
     */
    public void setEmpSal(double value) {
        this.empSal = value;
    }

}
