//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 03:05:17 PM IST 
//


package com.bhavna.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isIncreased" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hikePerc" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isIncreased",
    "hikePerc",
    "message"
})
@XmlRootElement(name = "EmployeeResponse")
public class EmployeeResponse {

    protected boolean isIncreased;
    protected double hikePerc;
    @XmlElement(required = true)
    protected String message;

    /**
     * Gets the value of the isIncreased property.
     * 
     */
    public boolean isIsIncreased() {
        return isIncreased;
    }

    /**
     * Sets the value of the isIncreased property.
     * 
     */
    public void setIsIncreased(boolean value) {
        this.isIncreased = value;
    }

    /**
     * Gets the value of the hikePerc property.
     * 
     */
    public double getHikePerc() {
        return hikePerc;
    }

    /**
     * Sets the value of the hikePerc property.
     * 
     */
    public void setHikePerc(double value) {
        this.hikePerc = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
